const helpers = require("../helpers");
const getNewMovements = helpers.getNewMovements;

const movements = [
  {
    canal: "",
    claveConcepto: "129",
    codigoAccionDetalleMovimientoCuenta: null,
    codigoTipoMovimiento: "1",
    concepto: "CR TRF INM COE",
    fecha: "21/10/2022",
    importe: "50,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "",
    saldo: "4.651,65",
    codigoSucursal: "733",
    tieneDetalle: false,
    denominacionCuenta: "",
    claveOperacion: null,
  },
  {
    canal: "",
    claveConcepto: "001",
    codigoAccionDetalleMovimientoCuenta: null,
    codigoTipoMovimiento: "0",
    concepto: "DB TRF INM COE",
    fecha: "21/10/2022",
    importe: "-50,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "",
    saldo: "4.601,65",
    codigoSucursal: "733",
    tieneDetalle: false,
    denominacionCuenta: "",
    claveOperacion: null,
  },
  {
    canal: "",
    claveConcepto: "129",
    codigoAccionDetalleMovimientoCuenta: null,
    codigoTipoMovimiento: "1",
    concepto: "CR TRF INM COE",
    fecha: "21/10/2022",
    importe: "100,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "",
    saldo: "4.651,65",
    codigoSucursal: "733",
    tieneDetalle: false,
    denominacionCuenta: "",
    claveOperacion: null,
  },
  {
    canal: "",
    claveConcepto: "001",
    codigoAccionDetalleMovimientoCuenta: null,
    codigoTipoMovimiento: "0",
    concepto: "DB TRF INM COE",
    fecha: "21/10/2022",
    importe: "-100,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "",
    saldo: "4.551,65",
    codigoSucursal: "733",
    tieneDetalle: false,
    denominacionCuenta: "",
    claveOperacion: null,
  },
  {
    canal: "",
    claveConcepto: "129",
    codigoAccionDetalleMovimientoCuenta: null,
    codigoTipoMovimiento: "1",
    concepto: "CR TRF INM COE",
    fecha: "21/10/2022",
    importe: "100,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "",
    saldo: "4.651,65",
    codigoSucursal: "733",
    tieneDetalle: false,
    denominacionCuenta: "",
    claveOperacion: null,
  },
  {
    canal: "",
    claveConcepto: "001",
    codigoAccionDetalleMovimientoCuenta: null,
    codigoTipoMovimiento: "0",
    concepto: "DB TRF INM COE",
    fecha: "21/10/2022",
    importe: "-100,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "",
    saldo: "4.551,65",
    codigoSucursal: "733",
    tieneDetalle: false,
    denominacionCuenta: "",
    claveOperacion: null,
  },
  {
    canal: "CAJERO AUTOMATICO RED",
    claveConcepto: "136",
    codigoAccionDetalleMovimientoCuenta: "05",
    codigoTipoMovimiento: "1",
    concepto: "TRANSFERENCIA 20406759572 Nro:11110008",
    fecha: "17/10/2022",
    importe: "500,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "20406759572",
    saldo: "4.651,65",
    codigoSucursal: "733",
    tieneDetalle: true,
    denominacionCuenta: "20406759572",
    claveOperacion: null,
  },
  {
    canal: "CAJERO AUTOMATICO RED",
    claveConcepto: "136",
    codigoAccionDetalleMovimientoCuenta: "05",
    codigoTipoMovimiento: "1",
    concepto: "TRANSFERENCIA 27406400358 Nro:11110008",
    fecha: "11/10/2022",
    importe: "36.000,00",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "733 - ",
    procedencia: "      ",
    referencia: "27406400358",
    saldo: "4.151,65",
    codigoSucursal: "733",
    tieneDetalle: true,
    denominacionCuenta: "27406400358",
    claveOperacion: null,
  },
  {
    canal: "",
    claveConcepto: "744",
    codigoAccionDetalleMovimientoCuenta: "14",
    codigoTipoMovimiento: "0",
    concepto: "PAGO VISA R303 CAJA B MOV W Nro:00311875",
    fecha: "11/10/2022",
    importe: "-32.568,29",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: "00001",
    origen: "100 - BANCA ONLINE",
    procedencia: "      ",
    referencia: "",
    saldo: "-31.848,35",
    codigoSucursal: "100",
    tieneDetalle: true,
    denominacionCuenta: "",
    claveOperacion: null,
  },
  {
    canal: "",
    claveConcepto: "236",
    codigoAccionDetalleMovimientoCuenta: null,
    codigoTipoMovimiento: "0",
    concepto: "IVA TASA GENERAL",
    fecha: "04/10/2022",
    importe: "-125,82",
    numeroCheque: null,
    numeroCuenta: "",
    numeroOperacion: null,
    origen: "39 - PLAZA ROMA",
    procedencia: "      ",
    referencia: "",
    saldo: "719,94",
    codigoSucursal: "039",
    tieneDetalle: false,
    denominacionCuenta: "",
    claveOperacion: null,
  },
];

test("No new movements", () => {
  lastMovement = movements[0];

  expect(getNewMovements(lastMovement, movements).length).toBe(0);
});

test("One new movement", () => {
  lastMovement = movements[1];

  expect(getNewMovements(lastMovement, movements).length).toBe(1);
});

test("Two new movements", () => {
  lastMovement = movements[2];

  expect(getNewMovements(lastMovement, movements).length).toBe(2);
});
